# Generated by Django 3.0.8 on 2021-06-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='notif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='profile_pic',
            field=models.ImageField(default='avatar.png', upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Developer', 'Developer'), ('Manager', 'Manager'), ('QA', 'QA')], default='Developer', max_length=20),
        ),
    ]
